# Generated by Django 6.0.1 on 2026-03-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_wallettransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
