# Generated by Django 6.0.1 on 2026-03-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_order_status_alter_user_role_deliveryboy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=40, max_digits=6)),
                ('free_delivery_above', models.DecimalField(decimal_places=2, default=500, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Delivery Settings',
            },
        ),
    ]
