"""
Django settings for fishmart project.
<<<<<<< HEAD
"""

from pathlib import Path
from datetime import timedelta
import os
=======

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
>>>>>>> 6be25334d9c8bb8dbb6252b2202710f68d09f422

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


<<<<<<< HEAD
# =======================
# SECURITY
# =======================

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-09g#wjn&9ru=r&!e30dz)wee2qtqoftyl)i^%l#cje1ux_ugc*')

DEBUG = True

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'api.User'


# =======================
# INSTALLED APPS
# =======================

INSTALLED_APPS = [
    'jazzmin',
=======
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-09g#wjn&9ru=r&!e30dz)wee2qtqoftyl)i^%l#cje1ux_ugc*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
>>>>>>> 6be25334d9c8bb8dbb6252b2202710f68d09f422
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
<<<<<<< HEAD
    'api',
]


# =======================
# MIDDLEWARE
# =======================

SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
=======
    'api'


]

MIDDLEWARE = [
>>>>>>> 6be25334d9c8bb8dbb6252b2202710f68d09f422
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
<<<<<<< HEAD
]

CORS_ALLOW_ALL_ORIGINS = True


# =======================
# JAZZMIN ADMIN UI
# =======================

JAZZMIN_SETTINGS = {
    "site_title": "FishMart Admin",
    "site_header": "FishMart",
    "site_brand": "FishMart",
    "welcome_sign": "Welcome to FishMart Admin",
    "copyright": "FishMart © 2026",
    "topmenu_links": [
        {"name": "Home", "url": "/", "permissions": ["auth.view_user"]},
        {"name": "Support", "url": "https://fishmart.example.com"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
}


# =======================
# URLS & TEMPLATES
# =======================

=======
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]


CORS_ALLOW_ALL_ORIGINS = True


>>>>>>> 6be25334d9c8bb8dbb6252b2202710f68d09f422
ROOT_URLCONF = 'fishmart.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fishmart.wsgi.application'


<<<<<<< HEAD
# =======================
# DATABASE
# =======================
=======
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
>>>>>>> 6be25334d9c8bb8dbb6252b2202710f68d09f422

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


<<<<<<< HEAD
# =======================
# PASSWORD VALIDATION
# =======================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# =======================
# INTERNATIONALIZATION
# =======================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# =======================
# STATIC & MEDIA FILES
# =======================
=======
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
>>>>>>> 6be25334d9c8bb8dbb6252b2202710f68d09f422

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

<<<<<<< HEAD
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =======================
# REST FRAMEWORK & JWT
# =======================
=======
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
RAZORPAY_KEY_ID = "rzp_test_xxxxx"
RAZORPAY_KEY_SECRET = "xxxxxxxx"
from datetime import timedelta
>>>>>>> 6be25334d9c8bb8dbb6252b2202710f68d09f422

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
<<<<<<< HEAD
}

=======
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}


>>>>>>> 6be25334d9c8bb8dbb6252b2202710f68d09f422
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}
<<<<<<< HEAD


# =======================
# EMAIL CONFIG
# =======================

=======
>>>>>>> 6be25334d9c8bb8dbb6252b2202710f68d09f422
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
<<<<<<< HEAD
EMAIL_HOST_USER = 'learnmore2016015@gmail.com'
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'zklx toti wccv khds')


# =======================
# RAZORPAY
# =======================

RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID', 'rzp_test_e664V0FP0zQy7N')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET', 'QdnuRxUHrPGeiJc9lDTXYPO7')


# =======================
# TWILIO — WHATSAPP OTP
# =======================

TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', 'YAHAN_APNA_NAYA_SID_DAALO')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', 'YAHAN_APNA_AUTH_TOKEN_DAALO')
TWILIO_WHATSAPP_NUMBER = "whatsapp:+14155238886"


# =======================
# CONTACT INFO
# =======================

CONTACT_EMAIL = 'altafmansoori04@gmail.com'
CONTACT_PHONES = ['8340729468']
=======

EMAIL_HOST_USER = 'learnmore2016015@gmail.com'
EMAIL_HOST_PASSWORD = 'zklx toti wccv khds'


import os

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
>>>>>>> 6be25334d9c8bb8dbb6252b2202710f68d09f422
